### ISSUE TITLE
Evolution costs

### ISSUE THREAD

**Issue by BASTAHT** [justinleewells/pogo-optimizer#190]
After evolution you get 1 candy back, probably because you get a new pokemon or something like that. Due to this the evolution actually costs 1 candy less than shown. So for example a pidgey only costs 11 candy instead of 12, increasing the possible evolutions by a lot.
One thing to take care of is that you do need 12 or more candies to actually evolve, so you cant simply divide by 11, cause for the last one you will need 12 candies, so for 2 pidgey evolutions you need 23 candy. The first one costs 12, which leaves you with 11, but you get one candy back and have 12 again, being able to evolve another one.

**Comment by BASTAHT** [comment]
Next to this, if you have exactly enough candy, the evos shows zero.
And when you have 0 candies, the evos shows -1

**Comment by azmihafizha** [comment]
this can be simply fixed by modifying the angular frontend, which i already done, including showing the sum of total evolution you can do, but seeing that the lucky egg calculator is already on the to do list, i think i dont need to make a pull request for a small feature like this and also to avoid work redundancy, which i believe justin is currently working on it

**Comment by jnsnow** [comment]
Duplicate of #174. See PR #182.

If you want an /exhaustive/ transfer calc, we don't calculate that, because it's not the best way to calculate evolutions. Why?

Because you have to re-transfer the Pidgeotto you created, but that takes time -- it's not efficient egg usage. I posit that the best evolution calculator simply guides you to optimizing your next Lucky Egg.

If you still want an exhaustive transfer calculation, it should be an option, but absolutely not the default.

**Comment by BASTAHT** [comment]
It is not about tranfering the pidgeotto, if you check it you will see that when you start with for example 20 pidgey candy and you evolve a pidgey you will have 9 candy afterwards, making the netto cost for a transfer only 11 instead of 12. When you do a lot of evolutions (of the same pokemon) this difference will be significant.

**Comment by jnsnow** [comment]
Oh, wow, I never noticed that. (Honestly that seems kind of like a bug...!)

OK, you still can't quite just divide by 11, but point taken. My PR counts transferring excess (prior to starting a lucky egg) and gives a modest boost over the base numbers, and this boosts it just a touch more.

**Comment by ferazambuja** [comment]
Are any plans to add a kind of calculator function on the evolution module?
I believe is the next step to be a real optimizer.
